name: "Apply divestOS patches"

on:
  workflow_dispatch:  # button shown only when in default branch

# Sets permissions of the GITHUB_TOKEN to allow pushing via github token
permissions:
  contents: write # allow git push

jobs:
  sync:
    runs-on: ubuntu-latest
    name: "Get divest + AXP patches"

    steps:
        
    - name: Checkout dOS
      uses: actions/checkout@v4
      with:
        path: dos
        repository: AXP-OS/build
        #ref: ${{ github.head_ref || github.ref_name }}
        submodules: true
        lfs: true

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: dos/Build/LineageOS-20.0/kernel/google/gs201/private
        submodules: true
        lfs: true
  
    - name: Patch
      run: |
        cd dos/Build/LineageOS-20.0
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        ~/bin/repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
        source ../../Scripts/init.sh
